---
services:
  ssi_access_decision_point:
    server:
      host: "localhost"
      port: 5002
      debug: true
    credentials:
      verifiers:
        jwt:
          verify_vc_url: "http://vc_jwt_verifier:5003/verify/vc/?jwt={jwt_vc}"
          verify_vp_only_url: "http://vc_jwt_verifier:5003/verify/vp/?verify_vcs=false&jwt={jwt_vp}"
          verify_vp_complete_url: "http://vc_jwt_verifier:5003/verify/vp/?verify_vcs=true&jwt={jwt_vp}"
    logging:
      level: DEBUG
