---
services:
  ssi_access_decision_point:
    server:
      host: "localhost"
      port: 5002
      debug: true
    credentials:
      verifiers:
        jwt:
          verify_vc_url: "http://vc_jwt_verifier:5003/verify/vc/?jwt={jwt_vc}"
          verify_vp_url: "http://vc_jwt_verifier:5003/verify/vp/?verify_vcs={verify_credentials}&jwt={jwt_vp}"
    logging:
      level: DEBUG
